version: 2
updates:
- package-ecosystem: maven
  directory: "/coherence"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.apache.kafka:kafka_2.12
    versions:
    - 2.7.0
