/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.4).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.jbcnconf.realtime.dataservice.api;

import org.jbcnconf.realtime.dataservice.model.Error;
import org.jbcnconf.realtime.dataservice.model.StockResponseWrapper;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-05-08T05:59:09.630Z")

@Api(value = "stock", description = "the stock API")
public interface StockApi {

    @ApiOperation(value = "Creates a new user.", nickname = "stockStoreIdGet", notes = "", response = StockResponseWrapper.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = StockResponseWrapper.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Error.class) })
    @RequestMapping(value = "/api/v1/stock/{storeId}",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<StockResponseWrapper> stockStoreIdGet(@ApiParam(value = "Store Id", required = true) @PathVariable("storeId") Integer storeId);

}
